---
# tasks file for ansible-nerdfonts

- name: '[Darwin] Include Dependencies Installation playbook'
  include_tasks: dependencies.yml
  become: no
  tags:
      - nerdfonts
      - nerdfonts_dependencies

- name: '[Darwin] Tap caskroom/fonts'
  homebrew_tap: name=caskroom/fonts state=present
  become: no
  tags:
    - nerdfonts

- name: '[Darwin] Install Nerd Fonts with homebrew cask'
  homebrew_cask: name="{{ item.caskname }}" state=upgraded update_homebrew=yes install_options=force
  become: no
  with_items: "{{ nerdfonts_fonts }}"
  tags:
    - nerdfonts

- name: '[Darwin] Install Mono Nerd Fonts with homebrew cask'
  homebrew_cask: name="{{ item.mono }}" state=upgraded update_homebrew=yes install_options=force
  become: no
  with_items: "{{ nerdfonts_fonts }}"
  when: nerdfonts_mono
  tags:
    - nerdfonts
...
